(() => {
  const state={data:null,cart:JSON.parse(localStorage.getItem('rt_cart_v1')||'[]')};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function saveCart(){localStorage.setItem('rt_cart_v1',JSON.stringify(state.cart));updateCartBadges()}
  function updateCartBadges(){$$('.cart-count').forEach(e=>e.textContent=state.cart.reduce((a,x)=>a+x.qty,0));}
  function toast(msg){const old=$('.toast');old?.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),3000)}
  async function load(){try{const r=await fetch('/api/bootstrap',{cache:'no-store'});if(!r.ok)throw 0;state.data=await r.json()}catch{state.data={products:[],categories:[],company:{},policy:{minOrderValue:2000,flatShippingFee:250}}}render();}
  function product(id){return state.data?.products?.find(p=>String(p.id)===String(id))}
  function add(id,qty=1){const p=product(id);if(!p)return;const row=state.cart.find(x=>String(x.id)===String(id));if(row)row.qty+=qty;else state.cart.push({id:p.id,qty});saveCart();toast(`${p.name} added to your order request.`);renderCartMini();}
  function remove(id){state.cart=state.cart.filter(x=>String(x.id)!==String(id));saveCart();render()}
  function setQty(id,qty){const row=state.cart.find(x=>String(x.id)===String(id));if(!row)return;if(qty<1)return remove(id);row.qty=Math.min(100,qty);saveCart();render()}
  function card(p){return `<article class="product"><a href="/product?id=${encodeURIComponent(p.id)}"><div class="product-media"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">${p.bestseller?'<span class="tag">BESTSELLER</span>':''}</div></a><div class="product-body"><h3>${esc(p.name)}</h3><p>${esc(p.size||p.category)}</p><div><span class="price">${money(p.price)}</span><span class="mrp">${money(p.mrp)}</span></div><div class="product-actions"><a class="btn btn-outline" href="/product?id=${encodeURIComponent(p.id)}">Details</a><button class="btn btn-gold" data-add="${p.id}">Add</button></div></div></article>`}
  function renderHome(){const d=state.data;const cats=$('#categories');if(cats)cats.innerHTML=d.categories.map(c=>`<a class="category" href="/products?category=${encodeURIComponent(c)}"><b>${esc(c)}</b><span>Explore collection →</span></a>`).join('');const grid=$('#featured');if(grid)grid.innerHTML=d.products.filter(p=>p.featured).slice(0,8).map(card).join('');}
  function renderProducts(){const host=$('#catalog');if(!host)return;const search=String($('#search')?.value||'').toLowerCase().trim();const active=$('.filter.active')?.dataset.cat||'';let ps=state.data.products.filter(p=>(!active||p.category===active)&&(!search||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(search)));$('#resultCount').textContent=`${ps.length} product${ps.length===1?'':'s'}`;host.innerHTML=ps.length?ps.map(card).join(''):`<div class="panel center" style="grid-column:1/-1;padding:55px"><h3>No matching products</h3><p class="muted">Try another category or search phrase.</p></div>`;}
  function renderProduct(){const host=$('#productDetail');if(!host)return;const id=new URLSearchParams(location.search).get('id')||state.data.products[0]?.id;const p=product(id);if(!p){host.innerHTML='<div class="panel">Product not found.</div>';return}host.innerHTML=`<div class="detail-media"><img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div><span class="eyebrow">${esc(p.category)}</span><h1>${esc(p.name)}</h1><p class="lead">${esc(p.description||'Premium festive selection from the RTCrackers catalogue.')}</p><div class="detail-price">${money(p.price)} <span class="mrp">${money(p.mrp)}</span></div><div class="chip">${esc(p.size||'Premium pack')} · ${p.rating||'—'}★ · ${p.reviewCount||0} reviews</div><div class="spacer"></div><div class="qty" data-product-qty><button data-q="-">−</button><span>1</span><button data-q="+">+</button></div><div class="spacer"></div><button class="btn btn-gold" id="detailAdd" data-add="${p.id}">Add to Order Request</button><a class="btn btn-outline" href="/order" style="margin-left:8px">View Order</a><div class="notice" style="margin-top:20px">Order requests are confirmed separately. No online payment gateway is used.</div></div>`;$('#detailAdd')?.addEventListener('click',()=>add(p.id,Number($('[data-product-qty] span')?.textContent||1)));$$('[data-q]').forEach(b=>b.addEventListener('click',()=>{const s=$('[data-product-qty] span');let n=Number(s.textContent)||1;n+=b.dataset.q==='+'?1:-1;s.textContent=Math.max(1,n)}));}
  function renderOrder(){const list=$('#orderLines');if(!list)return;const rows=state.cart.map(x=>({...x,p:product(x.id)})).filter(x=>x.p);if(!rows.length){list.innerHTML='<div class="panel center"><div style="font-size:45px">🛒</div><h3>Your order request is empty</h3><p class="muted">Browse the catalogue and add products to continue.</p><a class="btn btn-gold" href="/products">Explore Products</a></div>';$('#orderSummary')?.classList.add('hidden');return}$('#orderSummary')?.classList.remove('hidden');list.innerHTML=rows.map(x=>`<div class="line"><img src="${esc(x.p.image)}" alt=""><div><h4>${esc(x.p.name)}</h4><p>${money(x.p.price)} · ${esc(x.p.size||'')}</p><button class="btn btn-danger" data-remove="${x.id}" style="padding:6px 9px;font-size:11px">Remove</button></div><div class="qty"><button data-minus="${x.id}">−</button><span>${x.qty}</span><button data-plus="${x.id}">+</button></div></div>`).join('');const sub=rows.reduce((a,x)=>a+x.p.price*x.qty,0);const shipping=sub>=10000?0:250;$('#sumSubtotal').textContent=money(sub);$('#sumShipping').textContent=money(shipping);$('#sumTotal').textContent=money(sub+shipping);$('#minWarning').classList.toggle('hidden',sub>=2000);$$('[data-remove]').forEach(b=>b.onclick=()=>remove(b.dataset.remove));$$('[data-minus]').forEach(b=>b.onclick=()=>setQty(b.dataset.minus,(state.cart.find(x=>String(x.id)===String(b.dataset.minus))?.qty||1)-1));$$('[data-plus]').forEach(b=>b.onclick=()=>setQty(b.dataset.plus,(state.cart.find(x=>String(x.id)===String(b.dataset.plus))?.qty||1)+1));}
  function renderCartMini(){}
  function render(){updateCartBadges();renderHome();renderProducts();renderProduct();renderOrder();bindGlobal();}
  function bindGlobal(){const search=$('#search');search?.addEventListener('input',renderProducts);$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()});$$('[data-add]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.onclick=()=>add(b.dataset.add)});const menu=$('#menuBtn');menu?.addEventListener('click',()=>$('#mobileMenu')?.classList.toggle('show'));const clear=$('#clearCart');clear?.addEventListener('click',()=>{state.cart=[];saveCart();render()});const form=$('#orderForm');if(form&&!form.dataset.bound){form.dataset.bound='1';form.addEventListener('submit',submitOrder)} }
  async function ensureCheckoutSession(){try{const c=await fetch('/api/config').then(r=>r.json());if(!c.supabaseUrl||!c.supabasePublishableKey)return false;if(!window.supabase){await new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=fail;document.head.appendChild(s)})}const sb=window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const sess=await sb.auth.getSession();if(sess.data.session)return true;const r=await sb.auth.signInAnonymously();return !r.error}catch{return false}}
  async function submitOrder(e){e.preventDefault();if(state.cart.length===0)return;const sub=state.cart.reduce((a,x)=>a+(product(x.id)?.price||0)*x.qty,0);if(sub<2000){toast('Minimum order value is ₹2,000 after discount.');return}const fd=new FormData(e.currentTarget);const body={name:fd.get('name'),phone:fd.get('phone'),email:fd.get('email'),address:fd.get('address'),city:fd.get('city'),district:fd.get('district'),pincode:fd.get('pincode'),location:fd.get('location'),notes:fd.get('notes'),lines:state.cart};const btn=$('#submitOrder');btn.disabled=true;btn.textContent='Preparing secure session…';try{const sessionReady=await ensureCheckoutSession();if(!sessionReady)throw new Error('Order submission needs Supabase authentication to be configured. Please contact the site administrator.');btn.textContent='Submitting…';const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Order submission failed.');state.cart=[];saveCart();$('#orderFormWrap').classList.add('hidden');$('#confirmation').classList.remove('hidden');$('#orderRef').textContent=j.ref||j.id||'Submitted';}catch(err){toast(err.message)}finally{btn.disabled=false;btn.textContent='Submit Order Request'}}
  function initStartup(){const s=$('#startup');if(!s)return;const v=$('#startupVideo');const sound=$('#startupSound');let finished=false;const done=()=>{if(finished)return;finished=true;setTimeout(()=>s.classList.add('hide'),250)};const showSound=()=>sound?.classList.remove('hidden');const enableSound=()=>{if(!v)return;v.muted=false;v.volume=1;const p=v.play();if(p?.catch)p.catch(()=>{});sound?.classList.add('hidden')};v?.addEventListener('ended',done,{once:true});v?.addEventListener('error',()=>{s.classList.add('failed');done()},{once:true});sound?.addEventListener('click',enableSound,{once:true});const p=v?.play();if(p?.catch)p.catch(()=>{v.muted=true;showSound();v.play().catch(()=>{s.classList.add('failed');setTimeout(done,1200)})});setTimeout(done,4300);}
  async function init(){if(location.pathname==='/')initStartup();await load();const year=$('#year');if(year)year.textContent=new Date().getFullYear();}
  window.RTCrackers={add,remove,setQty,money};document.addEventListener('DOMContentLoaded',init);
})();
