(function(){
 const A=window.RTAdmin; if(!A)return; const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 async function api(path,opts={}){const s=await A.supabaseSession();const r=await fetch('/api/features'+path,{...opts,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`}});const j=await r.json();if(!r.ok||j.ok===false)throw Error(j.error||'Request failed');return j}
 const dt=id=>$(id)?.value?new Date($(id).value).toISOString():null;
 async function analytics(){try{const j=await api('/admin/analytics');const x=j.summary,s=j.series||{};const rows=(s.daily||[]).map(d=>`<tr><td>${esc(d.day)}</td><td>${d.orders}</td><td>₹${Number(d.sales).toLocaleString('en-IN')}</td></tr>`).join('');const tops=(s.topProducts||[]).map(d=>`<tr><td>${esc(d.name)}</td><td>${d.quantity}</td><td>₹${Number(d.sales).toLocaleString('en-IN')}</td></tr>`).join('');$('#featureAnalytics').innerHTML=`<div class="grid-form"><div><strong>Today's sales</strong><br>₹${x.todaySales.toLocaleString('en-IN')}</div><div><strong>Today's orders</strong><br>${x.todayOrders}</div><div><strong>Customers</strong><br>${x.totalCustomers}</div><div><strong>Average order</strong><br>₹${x.averageOrderValue.toFixed(0)}</div><div><strong>Pending</strong><br>${x.pendingOrders}</div><div><strong>Delivered</strong><br>${x.deliveredOrders}</div><div><strong>Coupon redemptions</strong><br>${x.couponUsage}</div><div><strong>Offers</strong><br>${x.offerCount}</div></div><div class="grid-form" style="margin-top:18px"><div><h3>Daily sales</h3><table><thead><tr><th>Day</th><th>Orders</th><th>Sales</th></tr></thead><tbody>${rows||'<tr><td colspan=3>No sales data</td></tr>'}</tbody></table></div><div><h3>Top products</h3><table><thead><tr><th>Product</th><th>Qty</th><th>Sales</th></tr></thead><tbody>${tops||'<tr><td colspan=3>No product data</td></tr>'}</tbody></table></div></div>`}catch(e){$('#featureAnalytics').textContent=e.message}}
 async function offers(){const j=await api('/admin/offers');$('#offerList').innerHTML=(j.items||[]).map(o=>`<div class="info-banner"><strong>${esc(o.name)}</strong> · ${esc(o.offer_type)} · ${o.value} · ${o.active?'ACTIVE':'INACTIVE'} <button class="btn btn-sm btn-outline feature-offer-duplicate" data-id="${o.id}">Duplicate</button> <button class="btn btn-sm btn-outline feature-offer-toggle" data-id="${o.id}" data-active="${o.active}">${o.active?'Deactivate':'Activate'}</button></div>`).join('')||'<p>No offers yet.</p>'}
 async function coupons(){const j=await api('/admin/coupons');$('#couponList').innerHTML=(j.items||[]).map(c=>`<div class="info-banner"><strong>${esc(c.code)}</strong> · ${esc(c.discount_type)} ${c.discount_value} · min ₹${c.min_order} · ${c.active?'ACTIVE':'INACTIVE'}</div>`).join('')||'<p>No coupons yet.</p>'}
 async function festivals(){const j=await api('/admin/festivals');$('#festivalList').innerHTML=(j.items||[]).map(f=>`<div class="info-banner"><strong>${esc(f.name)}</strong> · ${f.visible?'VISIBLE':'HIDDEN'} · ${f.end_at?new Date(f.end_at).toLocaleString('en-IN'):''}</div>`).join('')||'<p>No festival configuration yet.</p>'}
 async function reviews(){const j=await api('/admin/reviews');$('#reviewAdminList').innerHTML=(j.items||[]).map(r=>`<div class="info-banner"><strong>${esc(r.products?.name||'Product')}</strong> · ${'★'.repeat(r.rating)} · ${r.verified_purchase?'Verified':''}<p>${esc(r.comment)}</p><button class="btn btn-sm btn-primary review-status" data-id="${r.id}" data-status="approved">Approve</button> <button class="btn btn-sm btn-outline review-status" data-id="${r.id}" data-status="rejected">Reject</button> <button class="btn btn-sm btn-outline review-status" data-id="${r.id}" data-status="hidden">Hide</button></div>`).join('')||'<p>No reviews.</p>'}
 async function notifications(){const j=await api('/admin/notifications');$('#promoNotificationList').innerHTML=(j.items||[]).map(n=>`<div class="info-banner"><strong>${esc(n.title)}</strong> · ${n.active?'ACTIVE':'INACTIVE'}<p>${esc(n.message)}</p><small>Audience: ${esc(n.audience||'all')} · ${n.delivered_at?'Delivered':'Scheduled/ready'}</small><div style="margin-top:8px"><button class="btn btn-sm btn-outline notif-toggle" data-id="${n.id}" data-active="${n.active}">${n.active?'Deactivate':'Activate'}</button> <button class="btn btn-sm btn-outline notif-edit" data-id="${n.id}">Edit</button></div></div>`).join('')||'<p>No promotional notifications.</p>'}
 async function support(){try{const j=await api('/admin/support');$('#supportAdminList').innerHTML=(j.items||[]).length?(j.items||[]).map(x=>`<div class="info-banner"><strong>${esc(x.topic)}</strong> · ${esc(x.status)}<p>${esc(x.message)}</p><small>${x.customers?.name||''} ${x.customers?.email||''}</small><div style="margin-top:8px"><button class="btn btn-sm btn-outline support-reply" data-id="${x.id}">Reply</button> <select class="support-status" data-id="${x.id}"><option ${x.status==='open'?'selected':''}>open</option><option ${x.status==='in_progress'?'selected':''}>in_progress</option><option ${x.status==='resolved'?'selected':''}>resolved</option><option ${x.status==='closed'?'selected':''}>closed</option></select></div></div>`).join(''):'<p>No support requests.</p>'}catch(e){$('#supportAdminList').textContent=e.message}}
 document.addEventListener('DOMContentLoaded',()=>{
  $('#featureOfferForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/offers',{method:'POST',body:JSON.stringify({name:$('#foName').value,offer_type:$('#foType').value,value:$('#foValue').value,min_order:$('#foMin').value,start_at:dt('#foStart'),end_at:dt('#foEnd'),active:$('#foActive').checked})});e.target.reset();offers();alert('Offer created.')}catch(x){alert(x.message)}});
  $('#featureCouponForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/coupons',{method:'POST',body:JSON.stringify({code:$('#fcCode').value,discount_type:$('#fcType').value,discount_value:$('#fcValue').value,min_order:$('#fcMin').value,max_discount:$('#fcMax').value,start_at:dt('#fcStart'),end_at:dt('#fcEnd'),active:$('#fcActive').checked})});e.target.reset();coupons();alert('Coupon created.')}catch(x){alert(x.message)}});
  $('#featureFestivalForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/festivals',{method:'POST',body:JSON.stringify({name:$('#ffName').value,description:$('#ffDescription').value,start_at:dt('#ffStart'),end_at:dt('#ffEnd'),banner:$('#ffBanner').value,visible:$('#ffVisible').checked})});e.target.reset();festivals();alert('Festival published.')}catch(x){alert(x.message)}});
  $('#featureNotificationForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/notifications',{method:'POST',body:JSON.stringify({title:$('#fnTitle').value,message:$('#fnMessage').value,target_url:$('#fnUrl').value,audience:$('#fnAudience').value,start_at:dt('#fnStart'),end_at:dt('#fnEnd'),active:$('#fnActive').checked})});e.target.reset();notifications();alert('Notification published.')}catch(x){alert(x.message)}});
  document.addEventListener('click',async e=>{const r=e.target.closest('.review-status');if(r){try{await api('/admin/reviews/'+r.dataset.id,{method:'PATCH',body:JSON.stringify({status:r.dataset.status})});reviews()}catch(x){alert(x.message)}}const sr=e.target.closest('.support-reply');if(sr){const msg=prompt('Reply to customer');if(msg){try{await api('/admin/support/'+sr.dataset.id+'/messages',{method:'POST',body:JSON.stringify({message:msg})});support()}catch(x){alert(x.message)}}}const st=e.target.closest('.support-status');if(st){try{await api('/admin/support/'+st.dataset.id,{method:'PATCH',body:JSON.stringify({status:st.value})});support()}catch(x){alert(x.message)}}const nt=e.target.closest('.notif-toggle');if(nt){try{await api('/admin/notifications/'+nt.dataset.id,{method:'PATCH',body:JSON.stringify({active:nt.dataset.active!=='true'})});notifications()}catch(x){alert(x.message)}}const ne=e.target.closest('.notif-edit');if(ne){const title=prompt('Notification title');if(title!==null){const message=prompt('Notification message');if(message!==null){try{await api('/admin/notifications/'+ne.dataset.id,{method:'PATCH',body:JSON.stringify({title,message})});notifications()}catch(x){alert(x.message)}}}}const d=e.target.closest('.feature-offer-duplicate');if(d){try{await api('/admin/offers/'+d.dataset.id+'/duplicate',{method:'POST'});offers()}catch(x){alert(x.message)}}const o=e.target.closest('.feature-offer-toggle');if(o){try{await api('/admin/offers/'+o.dataset.id,{method:'PATCH',body:JSON.stringify({active:o.dataset.active!=='true'})});offers()}catch(x){alert(x.message)}}});
  const obs=new MutationObserver(()=>{const p=$('#tab-analytics.active');if(p&&!p.dataset.loaded){p.dataset.loaded=1;analytics()}const o=$('#tab-offers.active');if(o&&!o.dataset.loaded){o.dataset.loaded=1;offers()}const c=$('#tab-coupons.active');if(c&&!c.dataset.loaded){c.dataset.loaded=1;coupons()}const f=$('#tab-festivals.active');if(f&&!f.dataset.loaded){f.dataset.loaded=1;festivals()}const r=$('#tab-reviews.active');if(r&&!r.dataset.loaded){r.dataset.loaded=1;reviews()}const n=$('#tab-notifications.active');if(n&&!n.dataset.loaded){n.dataset.loaded=1;notifications()}const sp=$('#tab-support.active');if(sp&&!sp.dataset.loaded){sp.dataset.loaded=1;support()}});obs.observe(document.body,{attributes:true,subtree:true,attributeFilter:['class']});
 });
})();
