from __future__ import annotations
from datetime import datetime,date,time
from decimal import Decimal
from uuid import UUID
from sqlalchemy import BigInteger,Integer,SmallInteger,String,Text,Boolean,DateTime,Date,Time,Numeric,ForeignKey,Identity,JSON,CHAR
from sqlalchemy.dialects.postgresql import INET,UUID as PGUUID,JSONB
from sqlalchemy.orm import Mapped,mapped_column
from core.database import Base,TimestampMixin
class Order(Base,TimestampMixin):
 __tablename__='orders'; order_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); order_number:Mapped[str]=mapped_column(String(20),unique=True); user_id:Mapped[int]=mapped_column(BigInteger); billing_address_id:Mapped[int]=mapped_column(BigInteger); shipping_address_id:Mapped[int]=mapped_column(BigInteger); coupon_id:Mapped[int|None]=mapped_column(Integer); payment_method_id:Mapped[int]=mapped_column(SmallInteger); shipping_method_id:Mapped[int]=mapped_column(SmallInteger); subtotal:Mapped[Decimal]=mapped_column(Numeric(12,2)); discount_amount:Mapped[Decimal]=mapped_column(Numeric(12,2)); tax_amount:Mapped[Decimal]=mapped_column(Numeric(12,2)); shipping_amount:Mapped[Decimal]=mapped_column(Numeric(12,2)); total_amount:Mapped[Decimal]=mapped_column(Numeric(12,2)); payment_status:Mapped[str]=mapped_column(CHAR(1)); order_status:Mapped[str]=mapped_column(CHAR(1)); tracking_number:Mapped[str|None]=mapped_column(String(40)); expected_delivery_date:Mapped[date|None]=mapped_column(Date); delivery_date:Mapped[date|None]=mapped_column(Date); cancellation_reason:Mapped[str|None]=mapped_column(String(255)); notes:Mapped[str|None]=mapped_column(Text)
class OrderItem(Base,TimestampMixin):
 __tablename__='order_items'; order_item_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); order_id:Mapped[int]=mapped_column(BigInteger); product_id:Mapped[int]=mapped_column(BigInteger); variant_id:Mapped[int|None]=mapped_column(BigInteger); sku_snapshot:Mapped[str]=mapped_column(String(40)); product_name_snapshot:Mapped[str]=mapped_column(String(200)); quantity:Mapped[int]=mapped_column(Integer); mrp:Mapped[Decimal]=mapped_column(Numeric(12,2)); unit_price:Mapped[Decimal]=mapped_column(Numeric(12,2)); gst_percentage:Mapped[Decimal]=mapped_column(Numeric(5,2)); discount_amount:Mapped[Decimal]=mapped_column(Numeric(12,2)); tax_amount:Mapped[Decimal]=mapped_column(Numeric(12,2)); line_total:Mapped[Decimal]=mapped_column(Numeric(12,2))
class OrderStatusHistory(Base):
 __tablename__='order_status_history'; history_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); order_id:Mapped[int]=mapped_column(BigInteger); old_status:Mapped[str|None]=mapped_column(CHAR(1)); new_status:Mapped[str]=mapped_column(CHAR(1)); changed_by:Mapped[int|None]=mapped_column(Integer); remarks:Mapped[str|None]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime)
class Invoice(Base,TimestampMixin):
 __tablename__='invoices'; invoice_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); invoice_number:Mapped[str]=mapped_column(String(25),unique=True); order_id:Mapped[int]=mapped_column(BigInteger,unique=True); invoice_date:Mapped[date]=mapped_column(Date); customer_gstin:Mapped[str|None]=mapped_column(String(15)); invoice_pdf_url:Mapped[str|None]=mapped_column(String(500)); status:Mapped[str]=mapped_column(CHAR(1)); cancelled_at:Mapped[datetime|None]=mapped_column(DateTime); issued_by:Mapped[int|None]=mapped_column(Integer)

class Refund(Base,TimestampMixin):
 __tablename__='refunds'; refund_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); order_id:Mapped[int]=mapped_column(BigInteger); return_request_id:Mapped[int|None]=mapped_column(BigInteger); refund_amount:Mapped[Decimal]=mapped_column(Numeric(12,2)); refund_method:Mapped[str]=mapped_column(CHAR(1)); account_holder_name:Mapped[str|None]=mapped_column(String(120)); bank_name:Mapped[str|None]=mapped_column(String(100)); account_last4:Mapped[str|None]=mapped_column(String(4)); ifsc_code:Mapped[str|None]=mapped_column(String(11)); transaction_reference:Mapped[str|None]=mapped_column(String(60)); reason:Mapped[str|None]=mapped_column(String(255)); status:Mapped[str]=mapped_column(CHAR(1)); processed_by:Mapped[int|None]=mapped_column(Integer); processed_at:Mapped[datetime|None]=mapped_column(DateTime)
