from alembic import op
import sqlalchemy as sa
revision='0001_platform'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('rtc_hsn_codes',sa.Column('code',sa.String(20),primary_key=True),sa.Column('description',sa.String(500),nullable=False),sa.Column('gst_percentage',sa.Numeric(5,2),nullable=False),sa.Column('cess_percentage',sa.Numeric(5,2),nullable=False),sa.Column('is_active',sa.Boolean,nullable=False))
 op.create_table('rtc_payment_transactions',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('order_id',sa.BigInteger,index=True),sa.Column('user_id',sa.BigInteger,index=True),sa.Column('provider',sa.String(30),nullable=False),sa.Column('provider_payment_id',sa.String(100),unique=True),sa.Column('provider_order_id',sa.String(100),index=True),sa.Column('amount',sa.Numeric(12,2),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('method',sa.String(30)),sa.Column('failure_reason',sa.String(500)),sa.Column('raw_payload',sa.JSON),sa.Column('created_at',sa.DateTime,nullable=False),sa.Column('updated_at',sa.DateTime,nullable=False))
 op.create_table('rtc_payment_webhook_events',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('provider',sa.String(30),nullable=False),sa.Column('event_id',sa.String(150),unique=True,nullable=False),sa.Column('event_type',sa.String(100),nullable=False),sa.Column('payload',sa.JSON,nullable=False),sa.Column('signature_valid',sa.Boolean,nullable=False),sa.Column('processed_at',sa.DateTime),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('rtc_refund_requests',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('order_id',sa.BigInteger,index=True),sa.Column('payment_transaction_id',sa.BigInteger,sa.ForeignKey('rtc_payment_transactions.id')),sa.Column('user_id',sa.BigInteger),sa.Column('amount',sa.Numeric(12,2),nullable=False),sa.Column('reason',sa.String(500),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('provider_refund_id',sa.String(100)),sa.Column('notes',sa.Text),sa.Column('created_at',sa.DateTime,nullable=False),sa.Column('updated_at',sa.DateTime,nullable=False))
 op.create_table('rtc_return_requests',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('order_id',sa.BigInteger,index=True),sa.Column('order_item_id',sa.BigInteger),sa.Column('user_id',sa.BigInteger),sa.Column('return_type',sa.String(20),nullable=False),sa.Column('reason',sa.String(500),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('replacement_product_id',sa.BigInteger),sa.Column('tracking_number',sa.String(100)),sa.Column('notes',sa.Text),sa.Column('created_at',sa.DateTime,nullable=False),sa.Column('updated_at',sa.DateTime,nullable=False))
 op.create_table('rtc_loyalty_accounts',sa.Column('user_id',sa.BigInteger,primary_key=True),sa.Column('points_balance',sa.Integer,nullable=False),sa.Column('lifetime_earned',sa.Integer,nullable=False),sa.Column('tier',sa.String(20),nullable=False),sa.Column('updated_at',sa.DateTime,nullable=False))
 op.create_table('rtc_loyalty_ledger',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('user_id',sa.BigInteger,index=True),sa.Column('points',sa.Integer,nullable=False),sa.Column('transaction_type',sa.String(30),nullable=False),sa.Column('reference_type',sa.String(30)),sa.Column('reference_id',sa.String(80)),sa.Column('description',sa.String(255)),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('rtc_security_events',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('user_id',sa.BigInteger,index=True),sa.Column('event_type',sa.String(60),nullable=False),sa.Column('ip_address',sa.String(64)),sa.Column('user_agent',sa.String(500)),sa.Column('metadata_json',sa.JSON),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('rtc_revoked_tokens',sa.Column('jti',sa.String(120),primary_key=True),sa.Column('expires_at',sa.DateTime,index=True),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('rtc_file_objects',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('object_key',sa.String(500),unique=True,nullable=False),sa.Column('original_name',sa.String(255),nullable=False),sa.Column('content_type',sa.String(120),nullable=False),sa.Column('size_bytes',sa.BigInteger,nullable=False),sa.Column('url',sa.String(1000),nullable=False),sa.Column('owner_user_id',sa.BigInteger,index=True),sa.Column('purpose',sa.String(40),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('rtc_seo_records',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('entity_type',sa.String(30),nullable=False),sa.Column('entity_id',sa.String(80),nullable=False),sa.Column('meta_title',sa.String(160)),sa.Column('meta_description',sa.String(320)),sa.Column('canonical_url',sa.String(500)),sa.Column('robots',sa.String(100),nullable=False),sa.Column('og_image',sa.String(500)),sa.Column('updated_at',sa.DateTime,nullable=False),sa.UniqueConstraint('entity_type','entity_id',name='uq_rtc_seo_entity'))
 op.create_table('rtc_notification_deliveries',sa.Column('id',sa.BigInteger,sa.Identity(always=True),primary_key=True),sa.Column('user_id',sa.BigInteger,index=True),sa.Column('channel',sa.String(20),nullable=False),sa.Column('template',sa.String(80),nullable=False),sa.Column('destination',sa.String(255),nullable=False),sa.Column('payload',sa.JSON),sa.Column('status',sa.String(20),nullable=False),sa.Column('provider_id',sa.String(150)),sa.Column('error',sa.Text),sa.Column('created_at',sa.DateTime,nullable=False),sa.Column('sent_at',sa.DateTime))
def downgrade():
 for t in ['rtc_hsn_codes','rtc_notification_deliveries','rtc_seo_records','rtc_file_objects','rtc_revoked_tokens','rtc_security_events','rtc_loyalty_ledger','rtc_loyalty_accounts','rtc_return_requests','rtc_refund_requests','rtc_payment_webhook_events','rtc_payment_transactions']: op.drop_table(t)
