from __future__ import annotations
from datetime import datetime,date,time
from decimal import Decimal
from uuid import UUID
from sqlalchemy import BigInteger,Integer,SmallInteger,String,Text,Boolean,DateTime,Date,Time,Numeric,ForeignKey,Identity,JSON,CHAR
from sqlalchemy.dialects.postgresql import INET,UUID as PGUUID,JSONB
from sqlalchemy.orm import Mapped,mapped_column
from core.database import Base,TimestampMixin
class Product(Base,TimestampMixin):
 __tablename__='products'; product_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); category_id:Mapped[int]=mapped_column(Integer); subcategory_id:Mapped[int|None]=mapped_column(Integer); brand_id:Mapped[int|None]=mapped_column(Integer); sku:Mapped[str]=mapped_column(String(40),unique=True); barcode:Mapped[str|None]=mapped_column(String(32),unique=True); slug:Mapped[str]=mapped_column(String(200),unique=True); product_name:Mapped[str]=mapped_column(String(200)); short_description:Mapped[str|None]=mapped_column(String(500)); description:Mapped[str|None]=mapped_column(Text); mrp:Mapped[Decimal]=mapped_column(Numeric(12,2)); selling_price:Mapped[Decimal]=mapped_column(Numeric(12,2)); cost_price:Mapped[Decimal]=mapped_column(Numeric(12,2)); weight:Mapped[Decimal]=mapped_column(Numeric(10,3),default=0); is_featured:Mapped[bool]=mapped_column(Boolean,default=False); is_trending:Mapped[bool]=mapped_column(Boolean,default=False); is_new_arrival:Mapped[bool]=mapped_column(Boolean,default=False); status:Mapped[str]=mapped_column(CHAR(1),default='D'); stock_quantity:Mapped[int]=mapped_column(Integer,default=0); min_stock_level:Mapped[int]=mapped_column(Integer,default=0); sales_count:Mapped[int]=mapped_column(Integer,default=0); view_count:Mapped[int]=mapped_column(Integer,default=0)
class ProductImage(Base,TimestampMixin):
 __tablename__='product_images'; product_image_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); product_id:Mapped[int]=mapped_column(BigInteger); image_url:Mapped[str]=mapped_column(String(500)); alt_text:Mapped[str|None]=mapped_column(String(200)); is_primary:Mapped[bool]=mapped_column(Boolean,default=False); display_order:Mapped[int]=mapped_column(SmallInteger,default=0)
class ProductVariant(Base,TimestampMixin):
 __tablename__='product_variants'; variant_id:Mapped[int]=mapped_column(BigInteger,Identity(always=True),primary_key=True); product_id:Mapped[int]=mapped_column(BigInteger); variant_sku:Mapped[str]=mapped_column(String(40),unique=True); barcode:Mapped[str|None]=mapped_column(String(32),unique=True); variant_name:Mapped[str]=mapped_column(String(120)); pack_size:Mapped[int]=mapped_column(SmallInteger,default=1); mrp:Mapped[Decimal]=mapped_column(Numeric(12,2)); selling_price:Mapped[Decimal]=mapped_column(Numeric(12,2)); cost_price:Mapped[Decimal]=mapped_column(Numeric(12,2)); weight:Mapped[Decimal]=mapped_column(Numeric(10,3),default=0); is_active:Mapped[bool]=mapped_column(Boolean,default=True)
class ProductAttribute(Base,TimestampMixin):
 __tablename__='product_attributes'; attribute_id:Mapped[int]=mapped_column(Integer,Identity(always=True),primary_key=True); attribute_code:Mapped[str]=mapped_column(String(40),unique=True); attribute_name:Mapped[str]=mapped_column(String(80)); data_type:Mapped[str]=mapped_column(CHAR(1),default='T'); unit:Mapped[str|None]=mapped_column(String(20)); is_filterable:Mapped[bool]=mapped_column(Boolean,default=False); display_order:Mapped[int]=mapped_column(SmallInteger,default=0)
