from alembic import op
import sqlalchemy as sa
revision='0001_cms';down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table('cms_pages',sa.Column('page_id',sa.Integer(),sa.Identity(always=True),primary_key=True),sa.Column('slug',sa.String(160),nullable=False,unique=True),sa.Column('title',sa.String(200),nullable=False),sa.Column('content_html',sa.Text(),nullable=False),sa.Column('status',sa.CHAR(1),server_default='D',nullable=False),sa.Column('meta_title',sa.String(160)),sa.Column('meta_description',sa.String(320)),sa.Column('published_at',sa.DateTime()),sa.Column('updated_by',sa.Integer()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False))
 op.create_table('cms_home_sections',sa.Column('section_id',sa.Integer(),sa.Identity(always=True),primary_key=True),sa.Column('section_key',sa.String(80),nullable=False,unique=True),sa.Column('title',sa.String(150),nullable=False),sa.Column('content_json',sa.JSON(),nullable=False),sa.Column('display_order',sa.SmallInteger(),server_default='0',nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true',nullable=False),sa.Column('updated_by',sa.Integer()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False))
 op.create_table('cms_menus',sa.Column('menu_id',sa.Integer(),sa.Identity(always=True),primary_key=True),sa.Column('menu_key',sa.String(60),nullable=False,unique=True),sa.Column('menu_name',sa.String(100),nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true',nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False))
 op.create_table('cms_menu_items',sa.Column('item_id',sa.Integer(),sa.Identity(always=True),primary_key=True),sa.Column('menu_id',sa.Integer(),nullable=False),sa.Column('parent_item_id',sa.Integer()),sa.Column('label',sa.String(100),nullable=False),sa.Column('url',sa.String(500),nullable=False),sa.Column('display_order',sa.SmallInteger(),server_default='0',nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true',nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False))
 op.create_table('cms_footer_links',sa.Column('link_id',sa.Integer(),sa.Identity(always=True),primary_key=True),sa.Column('group_name',sa.String(80),nullable=False),sa.Column('label',sa.String(100),nullable=False),sa.Column('url',sa.String(500),nullable=False),sa.Column('display_order',sa.SmallInteger(),server_default='0',nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true',nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False))
 op.create_table('cms_faqs',sa.Column('faq_id',sa.Integer(),sa.Identity(always=True),primary_key=True),sa.Column('question',sa.String(500),nullable=False),sa.Column('answer_html',sa.Text(),nullable=False),sa.Column('display_order',sa.SmallInteger(),server_default='0',nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true',nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False))
 op.create_table('cms_policies',sa.Column('policy_id',sa.Integer(),sa.Identity(always=True),primary_key=True),sa.Column('policy_key',sa.String(60),nullable=False,unique=True),sa.Column('title',sa.String(150),nullable=False),sa.Column('content_html',sa.Text(),nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true',nullable=False),sa.Column('updated_by',sa.Integer()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False))
def downgrade():
 for t in ['cms_policies','cms_faqs','cms_footer_links','cms_menu_items','cms_menus','cms_home_sections','cms_pages']:op.drop_table(t)
